services:
  elephant-crawler-db-svc:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./svc/db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgress
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=elephant-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  elephant-crawler-core-api-svc:
    build:
      context: .
      dockerfile: ./svc/core-api/Dockerfile
    restart: always
    ports:
      - 8081:80
    environment:
      - DB_USER=postgress
      - DB_PASSWORD=password
      - DB_NAME=elephant-db
      - DB_PORT=5432
      - DB_HOST=elephant-crawler-db-svc
    depends_on:
      elephant-crawler-db-svc:
        condition: service_healthy

  elephant-crawler-crawlers-svc:
    build:
      context: .
      dockerfile: ./svc/crawlers/Dockerfile
    environment:
      - CORE_API_HOST=elephant-crawler-core-api-svc
      - CORE_API_PORT=80
    depends_on:
      - elephant-crawler-core-api-svc
